import {Inter} from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes"
import { Toaster } from "@/components/ui/sonner";

const inter= Inter({
  subsets: ["latin"]
});

export const metadata = {
  title: "AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
    }}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          
          <Header />
            
          <main className="min-h-screen">{children}</main>
          <Toaster richColors/>

          <footer className="bg-gradient-to-b from-muted/30 to-muted/60 border-t border-border/50 mt-8">
            <div className="container mx-auto px-6 py-12">
              {/* Main footer content */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
                {/* Brand section */}
                <div className="space-y-4">
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
                      <span className="text-white font-bold text-sm">AI</span>
                    </div>
                    <span className="font-bold text-xl bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
                      AI Career Coach
                    </span>
                  </div>
                  <p className="text-muted-foreground text-sm leading-relaxed max-w-sm">
                    Empowering your job search journey with cutting-edge AI tools for resumes, cover letters, and interview preparation.
                  </p>
                  <div className="flex gap-3">
                    <div className="w-8 h-8 bg-muted hover:bg-muted/70 rounded-full flex items-center justify-center cursor-pointer transition-colors">
                      <span className="text-xs">📧</span>
                    </div>
                    <div className="w-8 h-8 bg-muted hover:bg-muted/70 rounded-full flex items-center justify-center cursor-pointer transition-colors">
                      <span className="text-xs">🐦</span>
                    </div>
                    <div className="w-8 h-8 bg-muted hover:bg-muted/70 rounded-full flex items-center justify-center cursor-pointer transition-colors">
                      <span className="text-xs">💼</span>
                    </div>
                  </div>
                </div>

                {/* Navigation section */}
                <div className="space-y-4">
                  <h3 className="font-semibold text-foreground">Navigation</h3>
                  <nav className="flex flex-col space-y-2">
                    <a href="/" className="text-muted-foreground hover:text-foreground transition-colors text-sm hover:translate-x-1 transform duration-200">
                      Home
                    </a>
                    <a href="/dashboard" className="text-muted-foreground hover:text-foreground transition-colors text-sm hover:translate-x-1 transform duration-200">
                      Dashboard
                    </a>
                    <a href="/resume" className="text-muted-foreground hover:text-foreground transition-colors text-sm hover:translate-x-1 transform duration-200">
                      Resume Builder
                    </a>
                    <a href="/ai-cover-letter" className="text-muted-foreground hover:text-foreground transition-colors text-sm hover:translate-x-1 transform duration-200">
                      Cover Letter
                    </a>
                    <a href="/interview" className="text-muted-foreground hover:text-foreground transition-colors text-sm hover:translate-x-1 transform duration-200">
                      Interview Prep
                    </a>
                  </nav>
                </div>

                {/* Features section */}
                <div className="space-y-4">
                  <h3 className="font-semibold text-foreground">Features</h3>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <div className="w-1.5 h-1.5 bg-blue-500 rounded-full"></div>
                      AI-Powered Resume Analysis
                    </div>
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <div className="w-1.5 h-1.5 bg-green-500 rounded-full"></div>
                      Personalized Cover Letters
                    </div>
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <div className="w-1.5 h-1.5 bg-purple-500 rounded-full"></div>
                      Interview Coaching
                    </div>
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <div className="w-1.5 h-1.5 bg-orange-500 rounded-full"></div>
                      Career Guidance
                    </div>
                  </div>
                </div>
              </div>

              {/* Bottom bar */}
              <div className="pt-8 border-t border-border/50 flex flex-col md:flex-row items-center justify-between gap-4">
                <div className="text-sm text-muted-foreground">
                  &copy; {new Date().getFullYear()} AI Career Coach. All rights reserved.
                </div>
                <div className="flex items-center gap-6 text-sm text-muted-foreground">
                  <a href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</a>
                  <a href="/terms" className="hover:text-foreground transition-colors">Terms of Service</a>
                  <a href="/support" className="hover:text-foreground transition-colors">Support</a>
                </div>
              </div>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}